assembly/assembly-ide-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
assembly/assembly-ide-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java
assembly/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/ArtikMachineTerminalLauncher.java

@vparfonov @ashumilova Please review

Align assembly with CHE master. Fix build.

---

assembly/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

add usb bus to dev machine volumes
enable privilege mode by default
@azatsarynnyy @eivantsov Please take a look

CHE-1039: add usb bus to dev machine volumes

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java

Signed-off-by: Vitaliy Guliy <vguliy@codenvy.com>

CHE-999 SSH machines: handle exceptions on connections: properly subscribe to events

---

Vagrantfile
assembly/assembly-main/src/assembly/stacks/predefined-stacks.json

@riuvshin @ashumilova please take a look

Enable usb in VM, fixed broken base image reference for Android

---

plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/scp/PushToDeviceService.java

CHE-990: Fix error message during the first pushing of file to device

---

assembly/assembly-machine-war/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java
plugins/plugin-artik-ide/pom.xml
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/ArtikLocalizationConstant.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/discovery/DeviceDiscoveryServiceClient.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/discovery/DeviceDiscoveryServiceClientImpl.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/inject/ArtikGinModule.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesView.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesViewImpl.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesViewImpl.ui.xml
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/ArtikLocalizationConstant.properties
plugins/plugin-artik-server/pom.xml
plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/discovery/ArtikDeviceImpl.java
plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/discovery/DeviceDiscoverer.java
plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/discovery/DeviceDiscoveryService.java
plugins/plugin-artik-server/src/test/java/org/eclipse/che/plugin/machine/artik/discovery/DeviceDiscoveryServiceTest.java
plugins/plugin-artik-shared/src/main/java/org/eclipse/che/plugin/artik/shared/ArtikDevice.java
plugins/plugin-artik-shared/src/main/java/org/eclipse/che/plugin/artik/shared/dto/ArtikDeviceDto.java

Add Artik device discovery feature

---

.gitignore
Vagrantfile

@TylerJewell @eivantsov  please test this, I'm unable to test.

Use vagrant base image with preinstalled java, update .gitignore

---

Vagrantfile

Signed-off-by: Mykola Morhun <mmorhun@codenvy.com>

CODENVY-424: Configure Che Vagrant to setup Proxy

---

README.md

Updated links, images and added vagrant section.

Pre-release update to readme

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java

Signed-off-by: Vitaliy Guliy <vguliy@codenvy.com>

Ask machine status using timer to ensure machine is properly created

---

assembly/assembly-ide-war/src/main/webapp/IDE.jsp
assembly/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
assembly/assembly-machine-server/src/assembly/assembly.xml
assembly/assembly-machine-server/src/assembly/webapps/ROOT/WEB-INF/rewrite.config
assembly/assembly-machine-war/src/main/java/org/eclipse/che/wsagent/server/WsAgentServletModule.java
assembly/assembly-main/src/assembly/webapps/ROOT/WEB-INF/rewrite.config

Signed-off-by: Ann Shumilova <ashumilova@codenvy.com>

Update artik assembly

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java

Signed-off-by: Vitaliy Guliy <vguliy@codenvy.com>

CHE-1073 Deleting a running device does not delete it from Consoles and Machines widget

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesView.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesViewImpl.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesViewImpl.ui.xml

CHE-1077: remove save button, do autosave on connect, disable editing of connected device
Signed-off-by: Ann Shumilova <ashumilova@codenvy.com>

CHE-1077: remove save button, do autosave on connect

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesViewImpl.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesViewImpl.ui.xml

Signed-off-by: Ann Shumilova <ashumilova@codenvy.com>

CHE-1072: fix disabled state of host widget

---

plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/scp/PushToDeviceService.java

scp fix from 4.2.x

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java

Signed-off-by: Ann Shumilova <ashumilova@codenvy.com>

Add device name validation

---

Vagrantfile

The same has been done in Che. Porting these tweaks to Artik.

Add VM mount and backup workspaces, projects and prefs

---

assembly/assembly-ide-war/pom.xml

Signed-off-by: Vitaly Parfonov <vparfonov@codenvy.com>

CHE-747:Move ProjectTemplateService to separate module

---

assembly/assembly-ide-war/pom.xml
assembly/assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml

Related to https://github.com/eclipse/che/pull/1200

CHE-1112 remove usage of  che-core-api-account

---

Vagrantfile

1. Added curl test to verify that server has booted.
2. If curl test fails more than 5 times, then will attempt second start of the server.
3. Added in messages to make installation more helpful

Fix unexpxected suspend

---

assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java

@riuvshin Can you please merge my changes?

CODENVY-433 Adapt source code to acl of recipes

---

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

Add auto-snapshot and auto-restore the workspace state properties

---

assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java

Signed-off-by: Vitaly Parfonov <vparfonov@codenvy.com>

Adopt to last changes in Che repo

---

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

CHE-398: Add bindings for the workspace recovering,  without using the registry

---

plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/ArtikMachineInstanceProvider.java

Change-Id: Ie8994dd4e9e4097669c9da3a721cc7b6bba96848
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

CODENVY-560 InstanceProvider refactoring

---

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

@vparfonov @azatsarynnyy  please review

CODENVY-595: add missing props

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/inject/ArtikGinModule.java

Add binding for implementation of dummy links modifier
@skabashnyuk, @vparfonov

CODENVY-583: Fix javadoc navigation

---

assembly/assembly-wsagent-war/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java

CODENVY-583: Add bindings for wsagent.endpoint

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/updatesdk/TableResources.java
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/updatesdk/table.css

Fix license headers

---

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

Signed-off-by: Mykola Morhun <mmorhun@codenvy.com>

Change docker auth properties 

---

assembly/assembly-wsagent-server/src/assembly/server.xml
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/updatesdk/UpdateSDKPresenter.java
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/updatesdk/checkAvailableSdkVersionsCommand
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/updatesdk/checkSdkVersionOnDeviceCommand
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/updatesdk/installSdkOnDeviceCommand

Update commands for working with Artik SDK

---

Vagrantfile

This applies the Vagrantfile changes in Che from PR #1532 to the ARTIK Vagrantfile.
In addition to the changes in #1532, download progress for teh ARTIK Runtime SDK is shown the same way as for the rest of the downloads (this was silent before).

(#1531) Vagrantfile: Apply Che PR #1532 to ARTIK

---

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

CHE-1312: Add ability to configure credentials for several docker private registries

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/scp/action/ChooseTargetAction.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/scp/action/PushToDeviceAction.java

Resource manager

---

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

CHE-1353: Add possibility to configure api version by properties.

---

assembly/assembly-wsagent-war/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java
assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java

Adapt the code to UserService refactorings

---

assembly/assembly-ide-war/pom.xml
assembly/assembly-main/pom.xml
assembly/assembly-wsagent-server/pom.xml
assembly/assembly-wsagent-war/pom.xml
assembly/assembly-wsmaster-war/pom.xml
assembly/pom.xml
plugins/plugin-artik-help/pom.xml
plugins/plugin-artik-ide/pom.xml
plugins/plugin-artik-product-info/pom.xml
plugins/plugin-artik-server/pom.xml
plugins/plugin-artik-shared/pom.xml
plugins/pom.xml
pom.xml

Signed-off-by: Vitaly Parfonov <vparfonov@codenvy.com>
@eivantsov @riuvshin @TylerJewell

CHE-1360: Change artifactId and versionId

---

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties

Code and one property were changed in Che. This PR reflects these changes.
@eivantsov Please take a look

Fix properties after changes in Che

---

plugins/plugin-artik-ide/pom.xml
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/ArtikExtension.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/ArtikResources.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/inject/ArtikGinModule.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/AbstractResourceIndicator.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/ResourceIndicatorView.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/ResourceIndicatorViewImpl.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/ResourceIndicatorViewImpl.ui.xml
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/ResourceMonitor.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/ResourceMonitorService.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/updatesdk/SDKInstaller.java
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/resourcemonitor/cpu
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/resourcemonitor/memTotal
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/resourcemonitor/memUsed
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/resourcemonitor/storageTotal
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/resourcemonitor/storageUsed
plugins/plugin-artik-ide/src/test/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/ResourceIndicatorViewImplTest.java
plugins/plugin-artik-ide/src/test/java/org/eclipse/che/plugin/artik/ide/resourcemonitor/ResourceMonitorServiceTest.java

Show system resources usage (CPU, memory and storage) for connected devices within the IDE
@vparfonov plz, review

CHE-1361: Show system resources usage for connected devices

---

assembly/assembly-wsagent-war/pom.xml
assembly/assembly-wsagent-war/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java

Use JGit implemenation as Native Git is being removed from Che: https://github.com/eclipse/che/issues/2033

CHE-2033 Remove Native Git implementation

---

assembly/assembly-main/src/assembly/templates/samples.json

Use https://github.com/artik-iot/artik-sdk-examples to clone all sample apps at once.

Use Artik GitHub repo to source sample files

---

plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/profile/turnOnDevelopmentProfile
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/profile/turnOnProductionProfile

Artik 710 do not have rsync on board, so we will install it in dev profile and remove in production profile

Add rsync to list of software to be installed in dev profile

---

artik-ide.bat
artik-ide.sh

Adds the Che CLI to the ARTIK repository.  Sets the values to the defaults so that you can copy, setup and run.
https://github.com/codenvy/artik-ide/issues/130

Added Che CLI

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java

Fire an event when the device is destroyed

CODENVY-106: make disconnect when the device is deleted

---

artik-ide.sh

Picks up changes from Eclipse Che to support allowing the CLI to run in directories controlled by root.

Added fix for tmp dir

---

plugins/plugin-artik-ide/pom.xml
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/inject/ArtikGinModule.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/orionplugin/ArtikOrionPlugin.java
plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/orionplugin/ArtikOrionPluginResource.java
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/orionplugin/style.css
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/public/artikOrionPlugin/artikPlugin.html
plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/public/artikOrionPlugin/lib/plugin.js
plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/keyworddoc/KeywordDocsService.java

Highlight Artik-specific keywords in the editor

---

assembly/assembly-wsagent-war/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java

Revert "Removed ApiEndpointProvider to avoid duplication "

---

plugins/plugin-artik-server/src/main/java/org/eclipse/che/plugin/machine/artik/replication/shell/ShellCommandExecutor.java

Changed exception for debug message when no rsync installed
Related issue: https://github.com/codenvy/artik-ide/issues/125

Changed exception for debug message when no rsync installed

---

assembly/assembly-main/src/assembly/bin/che.sh
assembly/assembly-wsagent-war/pom.xml
assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java

backport [commit](https://github.com/eclipse/che/commit/6eb6e5deee54279cdaeb5063a0b7a385a7a69bfd#diff-da99a0cfbf0259a3356ba61430573726L611)

Add binding of CheJpaInitializer

---

assembly/assembly-ide-war/pom.xml
assembly/assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml
plugins/plugin-artik-onboard/pom.xml
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/BuildInfo.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/OnboardtExtension.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/inject/OnboardGinModule.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/AccountServiceClient.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/AccountServiceClientImpl.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardAction.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardLocalizationConstant.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardPresenter.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardResources.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardView.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardViewImpl.java
plugins/plugin-artik-onboard/src/main/java/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardViewImpl.ui.xml
plugins/plugin-artik-onboard/src/main/resources/org/eclipse/che/plugin/artik/ide/ext/onboard/OnboardExtension.gwt.xml
plugins/plugin-artik-onboard/src/main/resources/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/OnboardLocalizationConstant.properties
plugins/plugin-artik-onboard/src/main/resources/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/onboard.css
plugins/plugin-artik-onboard/src/main/resources/org/eclipse/che/plugin/artik/ide/ext/onboard/client/onboard/onboard.svg
plugins/plugin-artik-onboard/src/main/resources/org/eclipse/che/plugin/artik/ide/ext/onboard/client/support/support.svg
plugins/pom.xml
pom.xml

This code commit by SRCX-IoTG for ARTIK IDE onboarding registration function, please review code, thanks.

This code commit by SRCX-IoTG for ARTIK IDE onboarding registration function, please review code, thanks.

---

plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/manage/ManageDevicesPresenter.java

Close automatically dialog window when the connection to device is a success
@vparfonov  pls take a look

ARTIK-215: Close automatically Device Manager window

---

dockerfiles/cli/scripts/pre_init.sh

Adapt to CHE-4175
